#include <stdio.h>
#include <conio.h>

void print_ascii_name(int ascii_code) {
    const char *names[] = {
        "NUL (Null character)",
        "SOH (Start of Header)",
        "STX (Start of Text)",
        "ETX (End of Text)",
        "EOT (End of Transmission)",
        "ENQ (Enquiry)",
        "ACK (Acknowledgment)",
        "BEL (Bell)",
        "BS  (Backspace)",
        "HT  (Horizontal Tab)",
        "LF  (Line Feed)",
        "VT  (Vertical Tab)",
        "FF  (Form Feed)",
        "CR  (Carriage Return)",
        "SO  (Shift Out)",
        "SI  (Shift In)",
        "DLE (Data Link Escape)",
        "DC1 (Device Control 1)",
        "DC2 (Device Control 2)",
        "DC3 (Device Control 3)",
        "DC4 (Device Control 4)",
        "NAK (Negative Acknowledgment)",
        "SYN (Synchronous Idle)",
        "ETB (End of Transmission Block)",
        "CAN (Cancel)",
        "EM  (End of Medium)",
        "SUB (Substitute)",
        "ESC (Escape)",
        "FS  (File Separator)",
        "GS  (Group Separator)",
        "RS  (Record Separator)",
        "US  (Unit Separator)",
        "Space",
        "!",
        "\"",
        "#",
        "$",
        "%",
        "&",
        "'",
        "(",
        ")",
        "*",
        "+",
        ",",
        "-",
        ".",
        "/",
        "0",
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        ":",
        ";",
        "<",
        "=",
        ">",
        "?",
        "@",
        "A",
        "B",
        "C",
        "D",
        "E",
        "F",
        "G",
        "H",
        "I",
        "J",
        "K",
        "L",
        "M",
        "N",
        "O",
        "P",
        "Q",
        "R",
        "S",
        "T",
        "U",
        "V",
        "W",
        "X",
        "Y",
        "Z",
        "[",
        "\\",
        "]",
        "^",
        "_",
        "`",
        "a",
        "b",
        "c",
        "d",
        "e",
        "f",
        "g",
        "h",
        "i",
        "j",
        "k",
        "l",
        "m",
        "n",
        "o",
        "p",
        "q",
        "r",
        "s",
        "t",
        "u",
        "v",
        "w",
        "x",
        "y",
        "z",
        "{",
        "|",
        "}",
        "~",
        "DEL (Delete)"
    };

    if (ascii_code >= 0 && ascii_code <= 127) {
        printf("ASCII: %d name: %s\n", ascii_code, names[ascii_code]);
    } else {
        printf(" %d  is not valid ASCII (0 - 127)\n", ascii_code);
    }
}

int main() {
    int ch;
    printf("press your keyboard to input a key\n");
    ch = getch();
    print_ascii_name(ch);
    return 0;
}