
/* eslint-disable */
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "8.2.0 (cc20b33184330d9af9852454eee62dd1)",
    buildSeed: 1725623383252,
    "wdosbox-x.wasm": {
        "size": 6304557,
        "gzSize": 2294344
    },
    "wdosbox-x.js": {
        "size": 230427,
        "gzSize": 54620
    },
    "wdosbox.wasm": {
        "size": 1467780,
        "gzSize": 499720
    },
    "wdosbox.js": {
        "size": 108170,
        "gzSize": 28965
    },
    "wlibzip.wasm": {
        "size": 112408,
        "gzSize": 52240
    },
    "wlibzip.js": {
        "size": 74095,
        "gzSize": 19630
    }
,
};
